//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiNARemont.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class additional_specialists
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public int specialist_user_id { get; set; }
        public int assigned_by_manager_id { get; set; }
        public Nullable<System.DateTime> assigned_at { get; set; }
        public string reason { get; set; }
    
        public virtual users users { get; set; }
        public virtual repair_requests repair_requests { get; set; }
        public virtual users users1 { get; set; }
    }
}
