//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiNARemont.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class deadline_extensions
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public System.DateTime old_deadline { get; set; }
        public System.DateTime new_deadline { get; set; }
        public string extension_reason { get; set; }
        public int manager_id { get; set; }
        public Nullable<bool> client_agreed { get; set; }
        public Nullable<System.DateTime> client_agreement_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual users users { get; set; }
        public virtual repair_requests repair_requests { get; set; }
    }
}
