//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiNARemont.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_types
    {
        public equipment_types()
        {
            this.repair_requests = new HashSet<repair_requests>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<repair_requests> repair_requests { get; set; }
    }
}
