//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiNARemont.Conn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquipmentRepairDBEntities : DbContext
    {
        public EquipmentRepairDBEntities()
            : base("name=EquipmentRepairDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<additional_specialists> additional_specialists { get; set; }
        public DbSet<deadline_extensions> deadline_extensions { get; set; }
        public DbSet<equipment_types> equipment_types { get; set; }
        public DbSet<fault_types> fault_types { get; set; }
        public DbSet<repair_requests> repair_requests { get; set; }
        public DbSet<request_comments> request_comments { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<service_feedbacks> service_feedbacks { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<users> users { get; set; }
    }
}
