//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiNARemont.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_comments
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public int user_id { get; set; }
        public string comment_text { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual repair_requests repair_requests { get; set; }
        public virtual users users { get; set; }
    }
}
