//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiNARemont.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_feedbacks
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public Nullable<bool> qr_code_generated { get; set; }
        public string qr_code_url { get; set; }
        public string google_form_url { get; set; }
        public Nullable<bool> feedback_received { get; set; }
        public Nullable<System.DateTime> feedback_date { get; set; }
    
        public virtual repair_requests repair_requests { get; set; }
    }
}
