//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiNARemont.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.additional_specialists = new HashSet<additional_specialists>();
            this.additional_specialists1 = new HashSet<additional_specialists>();
            this.deadline_extensions = new HashSet<deadline_extensions>();
            this.repair_requests = new HashSet<repair_requests>();
            this.repair_requests1 = new HashSet<repair_requests>();
            this.repair_requests2 = new HashSet<repair_requests>();
            this.request_comments = new HashSet<request_comments>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password_hash { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int role_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<additional_specialists> additional_specialists { get; set; }
        public virtual ICollection<additional_specialists> additional_specialists1 { get; set; }
        public virtual ICollection<deadline_extensions> deadline_extensions { get; set; }
        public virtual ICollection<repair_requests> repair_requests { get; set; }
        public virtual ICollection<repair_requests> repair_requests1 { get; set; }
        public virtual ICollection<repair_requests> repair_requests2 { get; set; }
        public virtual ICollection<request_comments> request_comments { get; set; }
        public virtual roles roles { get; set; }
    }
}
